---
title: "chp_code"
author: "Jacopo Priori"
date: "2024-05-01"
output: html_document
---

### SETUP

```{r setup}

knitr::opts_chunk$set(eval=TRUE, echo = TRUE, include = TRUE, warning=FALSE)
rm(list=ls())
```

### LIBRARIES

```{r}

library('tidyverse')
library('tidyr')
library('dplyr')
library('ggplot2')
library('scales')
```

### NL

```{r}

nl_h <- read.csv('NL_health.csv',sep=';', check.names = F)
nl_i <- read.csv('NL_income.csv',sep=';', check.names = F)
nl_e <- read.csv('NL_education.csv',sep=';', check.names = F)

nl_h_1 <- nl_h %>% select('nomem_encr', 'ch23p020') %>% rename('id' = 'nomem_encr', 'hinder' = 'ch23p020') %>% na.omit()
nl_e_1 <- nl_e %>% select('nomem_encr', 'cw23p005') %>% rename('id' = 'nomem_encr', 'education' = 'cw23p005') %>% na.omit()
nl_i_1 <- nl_i %>% select('nomem_encr', 'ci23p372') %>% rename('id' = 'nomem_encr', 'income' = 'ci23p372') %>% na.omit()

nl_h_e <- merge(nl_h_1, nl_e_1, by = "id")
nl <- merge(nl_h_e, nl_i_1, by = "id")
```

### US

```{r}

us_h_e <- read.csv('US_health_educ.csv',sep=',', check.names = F)
us_i <- read.csv('US_inc.csv',sep=',', check.names = F)
```


```{r}

us_i_1 <- us_i %>% select('NAME_E', 'GISJOIN', 'AQRKE001') %>% rename('tract_name' = 'NAME_E', 'tract_id' = 'GISJOIN', 'inc' = 'AQRKE001') %>% na.omit()

us_h_e_1 <- us_h_e %>%
      mutate('tract_name' = NAME_E) %>%
      mutate('tract_id' = GISJOIN) %>%
      mutate('tot_h' = ARFZE001) %>%
      mutate('tot_e' = AQ44E001) %>%
      mutate('eight' = AQ44E004 + AQ44E012 + AQ44E020 + AQ44E028 + AQ44E036 + AQ44E045 + AQ44E053 + AQ44E061 + AQ44E069 + AQ44E077) %>% 
      mutate('twelfth' = AQ44E005 + AQ44E013 + AQ44E021 + AQ44E029 + AQ44E037 + AQ44E046 + AQ44E054 + AQ44E062 + AQ44E070 + AQ44E078) %>%
      mutate('hs' = AQ44E006 + AQ44E014 + AQ44E022 + AQ44E030 + AQ44E038 + AQ44E047 + AQ44E055 + AQ44E063 + AQ44E071 + AQ44E079) %>%
      mutate('nd' = AQ44E007 + AQ44E015 + AQ44E023 + AQ44E031 + AQ44E039 + AQ44E048 + AQ44E056 + AQ44E064 + AQ44E072 + AQ44E080) %>%
      mutate('ad' = AQ44E008 + AQ44E016 + AQ44E024 + AQ44E032 + AQ44E040 + AQ44E049 + AQ44E057 + AQ44E065 + AQ44E073 + AQ44E081) %>%
      mutate('bd' = AQ44E009 + AQ44E017 + AQ44E025 + AQ44E033 + AQ44E041 + AQ44E050 + AQ44E058 + AQ44E066 + AQ44E074 + AQ44E082) %>%
      mutate('gd' = AQ44E010 + AQ44E018 + AQ44E026 + AQ44E034 + AQ44E042 + AQ44E051 + AQ44E059 + AQ44E067 + AQ44E075 + AQ44E083) %>%
      mutate('ins' = ARFZE004 + ARFZE007 + ARFZE010 + ARFZE013 + ARFZE016 + ARFZE019 + ARFZE022 + ARFZE025 + ARFZE028 + ARFZE032 + ARFZE035 + ARFZE038 + ARFZE041 + ARFZE044 + ARFZE047 + ARFZE050 + ARFZE053 + ARFZE056) %>%
      mutate('not_ins' = ARFZE005 + ARFZE008 + ARFZE011 + ARFZE014 + ARFZE017 + ARFZE020 + ARFZE023 + ARFZE026 + ARFZE029 + ARFZE033 + ARFZE036 + ARFZE039 + ARFZE042 + ARFZE045 + ARFZE048 + ARFZE051 + ARFZE054 + ARFZE057) %>%
      mutate('ins_rate' = ins / tot_h) %>%
      mutate('eight_rate' = eight / tot_e) %>%
      mutate('twelfth_rate' = twelfth / tot_e) %>%
      mutate('hs_rate' = hs / tot_e) %>%
      mutate('nd_rate' = nd / tot_e) %>%
      mutate('ad_rate' = ad / tot_e) %>%
      mutate('bd_rate' = bd / tot_e) %>%
      mutate('gd_rate' = gd / tot_e) %>%
      select('tract_name', 'tract_id','tot_e', 'eight', 'eight_rate', 'twelfth', 'twelfth_rate', 'hs', 'hs_rate', 'nd', 'nd_rate', 'ad', 'ad_rate', 'bd', 'bd_rate', 'gd', 'gd_rate', 'tot_h', 'ins', 'not_ins', 'ins_rate') %>%
      na.omit()

us_counts <- merge(us_i_1, us_h_e_1, by = "tract_id") %>% mutate('tract_name' = tract_name.x) %>% mutate('avg_inc' = inc / tot_e) %>% mutate(tract_name.y = NULL) %>% mutate(tract_name.x = NULL)
```

### INCOME

```{r}
summary(us_counts$avg_inc)

ggplot(us_counts)+
      geom_histogram(aes(x=avg_inc), bins=100)
```

### HEALTH

```{r}

summary(us_counts$tot_h)
summary(us_counts$ins)
summary(us_counts$not_ins)
summary(us_counts$ins_rate)

sum(us_counts$tot_h == 0)

ggplot(us_counts)+
      geom_histogram(aes(x=ins_rate), bins=100)

us_counts_1 <- us_counts[us_counts$tot_h != 0, ]
```

### EDUCATION

```{r}

summary(us_counts_1$tot_e)
summary(us_counts_1$eight_rate)
summary(us_counts_1$twelfth_rate)
summary(us_counts_1$hs_rate)
summary(us_counts_1$nd_rate)
summary(us_counts_1$ad_rate)
summary(us_counts_1$bd_rate)
summary(us_counts_1$gd_rate)


us_e_2 <- as.data.frame(colSums(us_counts_1[, c('eight', 'twelfth', 'hs', 'nd', 'ad', 'bd', 'gd')]))
colnames(us_e_2) <- "total_count"
ggplot(us_e_2, aes(x = factor(rownames(us_e_2), levels = c('eight', 'twelfth', 'hs', 'nd', 'ad', 'bd', 'gd')), y = total_count)) +
  geom_bar(stat = "identity")
```

### MATRIX

```{r}

us <- us_counts_1 %>%
      mutate('income' = rescale(avg_inc)) %>%
      mutate('health' = rescale(ins_rate)) %>%
      mutate('education' = rescale((0*eight + 1*twelfth + 2*hs + 3*nd + 4*ad + 5*bd + 6*gd) / tot_e)) %>%
      select('tract_id', 'income', 'health', 'education', 'tract_name')

head(us)

ggplot(us)+
      geom_histogram(aes(x=income), bins=100)
ggplot(us)+
      geom_histogram(aes(x=health), bins=100)
ggplot(us)+
      geom_histogram(aes(x=education), bins=100)

us_INCOME <- us %>% arrange(desc(income)) %>% select(income) %>% mutate('rank' = rank(income))
us_HEALTH <- us %>% arrange(desc(health)) %>% select(health) %>% mutate('rank' = rank(health))
us_EDUCATION <- us %>% arrange(desc(education)) %>% select(education) %>% mutate('rank' = rank(education))

write.csv(us, "US.csv", row.names = FALSE)
write.csv(us_INCOME, "US_INCOME.csv", row.names = FALSE)
write.csv(us_HEALTH, "US_HEALTH.csv", row.names = FALSE)
write.csv(us_EDUCATION, "US_EDUCATION.csv", row.names = FALSE)
```



